@startuml
title Choose Map
autonumber
actor Player

box "Client"
participant Admin
participant OtherLobbyPlayers
participant MapDB
end box

box "Server"
participant Lobby
endbox

activate Admin


Player -> Admin: requestChooseMap
Admin -> MapDB: requestChooseMap
activate MapDB 
MapDB --> Admin: return MapID
deactivate MapDB
Admin -> Lobby: requestChooseMap
activate Lobby
Lobby -> Lobby: setMap
note right Lobby
add mapID to property
end note 
activate Lobby 
Lobby -> OtherLobbyPlayers: NotifyMapChosen
deactivate Lobby
Lobby --> Admin: responseChooseMap
deactivate Lobby 
Admin --> Player: responseChooseMap


@enduml
