@startuml
title Choose Character
autonumber
actor Player

box "Client"
participant LobbyPlayer
participant OtherLobbyPlayers
participant CharacterDB
end box

box "Server"
participant Lobby
endbox

activate LobbyPlayer


Player -> LobbyPlayer: requestChooseCharacter
LobbyPlayer -> CharacterDB: requestChooseCharacter
activate CharacterDB 
CharacterDB --> LobbyPlayer: return characterID
deactivate CharacterDB 
LobbyPlayer -> LobbyPlayer: add CharacterID to property
LobbyPlayer -> Lobby: requestChooseCharacter
activate Lobby
Lobby -> Lobby: setCharacter
note right Lobby
add CharacterID to a map
with equivalent CharacterID
end note 
activate Lobby
Lobby -> OtherLobbyPlayers: NotifyCharacterChosen
deactivate Lobby
Lobby --> LobbyPlayer: responseChooseCharacter 
deactivate Lobby 

LobbyPlayer --> Player: responseChooseCharacter
@enduml
