@startuml
title Join Lobby 
autonumber
actor Player

box "Client"
participant ClientPlayer
participant LobbyPlayer
end box

box "Server"
participant LobbyManager
participant Lobby
endbox
activate LobbyManager

activate ClientPlayer


Player -> ClientPlayer: requestJoinRoom (roomName)


ClientPlayer -> LobbyManager : requestJoinRoom(roomName)


LobbyManager -> Lobby: AddPlayer(playerID)
activate Lobby 
Lobby -> Lobby: AddPlayertoListPlayer
note right Lobby
add PlayerID to listPlayer
end note 
Lobby --> LobbyManager: AddPlayer return(status)
deactivate Lobby 
LobbyManager --> ClientPlayer: requestJoinRoom(createRoomID, status)
ClientPlayer --> Player: requestJoinRoom
deactivate ClientPlayer
deactivate LobbyManager 
create LobbyPlayer
ClientPlayer -> LobbyPlayer : create instance

@enduml
