@startuml
title Kick Player
autonumber
actor Player

box "Client"
participant Admin
participant OtherLobbyPlayers
end box

box "Server"
participant Lobby
endbox

activate Admin

Player -> Admin: requestKickPlayer

Admin -> Lobby: requestKickPlayer
activate Lobby
Lobby -> Lobby: updateListPlayer
note right Lobby
deletePlayerID from list
end note 
activate Lobby 
Lobby -> OtherLobbyPlayers: NotifyPlayerKicked 
deactivate Lobby
Lobby --> Admin: responseKickPlayer
deactivate Lobby  
Admin --> Player: responseKickPlayer
deactivate Admin

@enduml
