@startuml
title Leave Room
autonumber
actor Player

box "Client"
participant LobbyPlayer
participant OtherLobbyPlayers
end box

box "Server"
participant Lobby
endbox

activate LobbyPlayer


Player -> LobbyPlayer: requestLeaveRoom
LobbyPlayer -> Lobby: requestLeaveRoom

activate Lobby
Lobby -> Lobby: updateListPlayer
note right Lobby
remove PlayerID in list
end note 
activate Lobby
Lobby -> OtherLobbyPlayers: NotifyCharacterLeave
deactivate Lobby
Lobby --> LobbyPlayer: responseLeaveCharacter 
deactivate Lobby 
LobbyPlayer --> Player: responseLeaveRoom
deactivate LobbyPlayer 

@enduml
